// VerifyReport.jsx — SSLVault public report verification (TrustSeal)
// Anyone can paste a report's SHA-256 integrity code (or the 8-char seal code)
// to confirm the report was genuinely generated by SSLVault Compliance Witness.
import { useState } from 'react'
import { ShieldCheck, ShieldAlert, Search, Loader2, FileCheck2, Globe, Calendar, Hash } from 'lucide-react'

const SB_URL = 'https://frthcwkntciaakqsppss.supabase.co'
const FN     = SB_URL + '/functions/v1/compliance-witness'
const F      = "'DM Sans','Inter',system-ui,sans-serif"
const MONO   = "'JetBrains Mono','Fira Mono',monospace"
const BLUE   = '#0077b6'
const BORDER = 'rgba(0,119,182,0.12)'

export default function VerifyReport() {
  const [code,    setCode]    = useState('')
  const [loading, setLoading] = useState(false)
  const [result,  setResult]  = useState(null) // { valid, generated_at, stats, package_hash, domain_scope }
  const [error,   setError]   = useState('')

  async function verify() {
    const clean = code.trim().toLowerCase().replace(/[^0-9a-f]/g, '')
    if (clean.length < 8) { setError('Enter at least the 8-character seal code (or the full 64-character integrity code).'); return }
    setLoading(true); setError(''); setResult(null)
    try {
      const r = await fetch(`${FN}?verify=${encodeURIComponent(clean)}`)
      const data = await r.json()
      if (data && data.ok) setResult(data)
      else setError(data?.error || 'Verification service is unavailable right now. Please try again shortly.')
    } catch {
      setError('Verification service is unavailable right now. Please try again shortly.')
    }
    setLoading(false)
  }

  const fmtT = iso => { try { return new Date(iso).toLocaleString('en-GB', { day:'2-digit', month:'long', year:'numeric', hour:'2-digit', minute:'2-digit' }) } catch { return iso } }

  return (
    <div style={{ minHeight:'100vh', background:'#f0f4fa', fontFamily:F, display:'flex', flexDirection:'column', alignItems:'center', padding:'56px 20px' }}>

      {/* Header */}
      <div style={{ textAlign:'center', maxWidth:560, marginBottom:28 }}>
        <div style={{ width:64, height:64, borderRadius:'50%', background:'#fff', border:`2px solid ${BLUE}`, display:'flex', alignItems:'center', justifyContent:'center', margin:'0 auto 16px', boxShadow:'0 4px 16px rgba(0,119,182,0.12)' }}>
          <ShieldCheck size={30} color={BLUE}/>
        </div>
        <h1 style={{ fontSize:26, fontWeight:800, color:'#0d1117', margin:'0 0 8px' }}>Verify a Compliance Report</h1>
        <p style={{ fontSize:14, color:'#5a6776', lineHeight:1.6, margin:0 }}>
          Every report generated by SSLVault Compliance Witness carries a tamper-evident integrity code.
          Paste the full SHA-256 code from the report footer — or the 8-character code printed inside the seal — to
          confirm the report is genuine and unaltered.
        </p>
      </div>

      {/* Input card */}
      <div style={{ width:'100%', maxWidth:560, background:'#fff', border:`1px solid ${BORDER}`, borderRadius:14, padding:'22px 24px', boxShadow:'0 2px 12px rgba(13,17,23,0.04)' }}>
        <label style={{ display:'block', fontSize:10, fontWeight:700, color:'#7a8694', textTransform:'uppercase', letterSpacing:'0.06em', marginBottom:8 }}>
          Integrity code or seal code
        </label>
        <div style={{ display:'flex', gap:10 }}>
          <input
            value={code}
            onChange={e => { setCode(e.target.value); setError(''); }}
            onKeyDown={e => { if (e.key === 'Enter') verify() }}
            placeholder="e.g. A8D42F2B or the full 64-character code"
            spellCheck={false}
            style={{ flex:1, padding:'12px 14px', borderRadius:10, border:`1.5px solid ${BORDER}`, fontSize:13, fontFamily:MONO, color:'#0d1117', outline:'none', background:'#f8fafd' }}
          />
          <button onClick={verify} disabled={loading}
            style={{ display:'flex', alignItems:'center', gap:7, padding:'12px 20px', borderRadius:10, fontSize:13, fontWeight:700, cursor: loading ? 'wait' : 'pointer', fontFamily:F, background:BLUE, border:'none', color:'#fff' }}>
            {loading ? <Loader2 size={15} style={{ animation:'spin 1s linear infinite' }}/> : <Search size={15}/>}
            Verify
          </button>
        </div>
        {error && <div style={{ marginTop:10, fontSize:12.5, color:'#b03425' }}>{error}</div>}
      </div>

      {/* Result */}
      {result && (
        <div style={{ width:'100%', maxWidth:560, marginTop:18 }}>
          {result.valid ? (
            <div style={{ background:'#f0faf4', border:'1px solid #bfe5cd', borderRadius:14, padding:'22px 24px' }}>
              <div style={{ display:'flex', alignItems:'center', gap:12, marginBottom:14 }}>
                <div style={{ width:44, height:44, borderRadius:'50%', background:'rgba(0,165,80,0.1)', display:'flex', alignItems:'center', justifyContent:'center', flexShrink:0 }}>
                  <FileCheck2 size={22} color="#00a550"/>
                </div>
                <div>
                  <div style={{ fontSize:16, fontWeight:800, color:'#1a7d43' }}>Report verified ✓</div>
                  <div style={{ fontSize:12, color:'#3d4a58' }}>This integrity code matches a report genuinely generated by SSLVault Compliance Witness.</div>
                </div>
              </div>
              <div style={{ display:'grid', gridTemplateColumns:'1fr 1fr', gap:10 }}>
                <Fact icon={<Calendar size={13}/>} k="Generated" v={fmtT(result.generated_at)} />
                <Fact icon={<Globe size={13}/>}    k="Scope"     v={result.domain_scope || 'All account domains'} />
                <Fact icon={<ShieldCheck size={13}/>} k="Domains / Events" v={`${result.stats?.domains ?? '—'} domains · ${result.stats?.events ?? '—'} ledger events`} />
                <Fact icon={<ShieldCheck size={13}/>} k="Evidence score" v={`${result.stats?.avg_evidence_score ?? '—'}/100 · ${result.stats?.open_items ?? '—'} open items`} />
              </div>
              <div style={{ marginTop:12 }}>
                <div style={{ fontSize:10, fontWeight:700, color:'#7a8694', textTransform:'uppercase', letterSpacing:'0.06em', marginBottom:4, display:'flex', alignItems:'center', gap:5 }}><Hash size={11}/> Full integrity code</div>
                <div style={{ fontSize:10.5, fontFamily:MONO, color:'#3d4a58', wordBreak:'break-all', background:'#fff', border:'1px solid #bfe5cd', borderRadius:8, padding:'8px 12px' }}>{result.package_hash}</div>
              </div>
              <div style={{ marginTop:12, fontSize:11.5, color:'#5a6776', lineHeight:1.6 }}>
                If the code above does not exactly match the code printed in the report footer, the document you received was modified after generation.
              </div>
            </div>
          ) : (
            <div style={{ background:'#fdf1ef', border:'1px solid #eccac3', borderRadius:14, padding:'22px 24px' }}>
              <div style={{ display:'flex', alignItems:'center', gap:12 }}>
                <div style={{ width:44, height:44, borderRadius:'50%', background:'rgba(176,52,37,0.08)', display:'flex', alignItems:'center', justifyContent:'center', flexShrink:0 }}>
                  <ShieldAlert size={22} color="#b03425"/>
                </div>
                <div>
                  <div style={{ fontSize:16, fontWeight:800, color:'#b03425' }}>No matching report found</div>
                  <div style={{ fontSize:12.5, color:'#3d4a58', lineHeight:1.6, marginTop:2 }}>
                    {result.reason === 'ambiguous_prefix'
                      ? 'This seal code matches more than one report — please enter the full 64-character integrity code from the report footer.'
                      : 'This code does not match any report in the registry. The document may have been altered, or the code was mistyped. Reports generated before June 2026 predate the public registry.'}
                  </div>
                </div>
              </div>
            </div>
          )}
        </div>
      )}

      {/* Footer note */}
      <div style={{ maxWidth:560, marginTop:28, fontSize:11.5, color:'#7a8694', textAlign:'center', lineHeight:1.7 }}>
        SSLVault Compliance Witness records every certificate lifecycle event in an append-only, hash-chained ledger.
        Report verification is public and requires no account.
        <br/><a href="/" style={{ color:BLUE, fontWeight:600, textDecoration:'none' }}>← Back to SSLVault</a>
      </div>

      <style>{`@keyframes spin{to{transform:rotate(360deg)}}`}</style>
    </div>
  )
}

function Fact({ icon, k, v }) {
  return (
    <div style={{ background:'#fff', border:'1px solid #bfe5cd', borderRadius:9, padding:'9px 12px' }}>
      <div style={{ fontSize:9.5, fontWeight:700, color:'#7a8694', textTransform:'uppercase', letterSpacing:'0.05em', display:'flex', alignItems:'center', gap:4, marginBottom:3 }}>{icon} {k}</div>
      <div style={{ fontSize:12.5, fontWeight:600, color:'#0d1117' }}>{v}</div>
    </div>
  )
}
