// BUILD_TIME: 1747000000
import { useState, useEffect } from 'react'
import { supabase } from './lib/supabase'
import Nav from './components/Nav'
import Home from './pages/Home'
import CLMHome from './pages/CLMHome'
import Import from './pages/Import'
import Dashboard from './pages/Dashboard'
import Auth from './pages/Auth'
import SharedHostingGuide from './pages/SharedHostingGuide'
import KnowledgeBase from './pages/KnowledgeBase'
import GetStarted from './pages/GetStarted'
import Install from './pages/Install'
import DnsProviders from './pages/DnsProviders'
import About from './pages/About'
import Contact from './pages/Contact'
import Developer from './pages/Developer'
import Privacy from './pages/Privacy'
import Terms from './pages/Terms'
import Pricing from './pages/Pricing'
import KeyLocker from './pages/KeyLocker'
import BuyCertificate from './pages/BuyCertificate'

export default function App() { return null }\n